#!/bin/bash
#
#SBATCH --mail-user=lawrencetang@uchicago.edu
#SBATCH --mail-type=ALL
#SBATCH --partition=titan
#SBATCH --mem-per-cpu=60000

export PATH=$PATH:/usr/local/cuda/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH=/usr/local/cuda/lib

srun python3 full_model.py
